from pathlib import Path
import os

# Assuming you run snakemake from NIH_ExPORTER_SM directory
PROJECT_ROOT = Path.cwd().resolve()
config["env_path"] = os.path.join(PROJECT_ROOT, "envs", "nih.yml")

print("Resolved absolute env path:", config["env_path"])

include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/metrics.smk"
include: "rules/keywords.smk"
include: "rules/mlexport.smk"