# Configuration for NIH ExPORTER Workflow

folder: data/raw

subfolders:
  - ClinicalStudies
  - Patents
  - PRJ
  - PRJABS
  - PUB
  - PUBLINK

rename_columns_map:
  CORE_PROJECT_NUM: PROJECT_NUMBER
  PROJECT_ID: PROJECT_NUMBER
  Core Project Number: PROJECT_NUMBER

keywords:
  treatment:
    - CRISPR
    - gene editing
    - genome editing
    - ASO
    - prime editor
    - base editor
    - gene therapy
    - gene editor
    - antisense oligonucleotide
    - cas9
  disease:
    - Abetalipoproteinemia
    - Acute Hepatic Porphyria
    - Aicardi Syndrome
    - Alagille Syndrome
    - Alkaptonuria
    - Alström Syndrome
    - Amyotrophic Lateral Sclerosis
    - Angelman Syndrome
    - Bardet-Biedl Syndrome
    - Batten Disease
    - Beckwith-Wiedemann Syndrome
    - Brugada Syndrome
    - CADASIL
    - Chronic Granulomatous Disease
    - Cri-du-chat Syndrome
    - Cystic Fibrosis
    - Duchenne Muscular Dystrophy
    - Ehlers-Danlos Syndrome
    - Epidermolysis Bullosa
    - Fabry Disease
    - Fragile X Syndrome
    - Friedreich's Ataxia
    - Gaucher Disease
    - Haemophilia
    - Hereditary Angioedema
    - Huntington's Disease
    - Hurler Syndrome
    - Incontinentia Pigmenti
    - inherited
    - Jumping Frenchmen of Maine
    - Kabuki Syndrome
    - Langerhans Cell Histiocytosis
    - Leigh Syndrome
    - Lesch-Nyhan Syndrome
    - Marfan Syndrome
    - monogenetic
    - Moyamoya Disease
    - Multiple System Atrophy
    - Neurofibromatosis
    - Niemann-Pick Disease
    - Ornithine Transcarbamylase Deficiency
    - orphan disease
    - Parry-Romberg Syndrome
    - Phenylketonuria
    - Pompe Disease
    - Prader-Willi Syndrome
    - Primary Ciliary Dyskinesia
    - Progeria
    - Pseudoxanthoma Elasticum
    - rare disease
    - Rett Syndrome
    - Sickle Cell Disease
    - Spinal Muscular Atrophy
    - Sturge-Weber Syndrome
    - Tay-Sachs Disease
    - Von Hippel-Lindau Disease
    - Wilson's Disease
    - Wolfram Syndrome

text_columns:
  - PROJECT_TITLE
  - PROJECT_TERMS
  - PHR
  - ABSTRACT_TEXT

ml_columns:
  - APPLICATION_ID
  - PHR
  - PROJECT_TERMS
  - PROJECT_TITLE
  - ABSTRACT_TEXT
  - total count
  - total unique count
  - flagged

# 🔧 Workflow toggles
force_append: true 
parallel: true
remove_duplicates: true
finalize_drop_output: true
use_stopwords: true
cutoff_value: 1

# 🧪 Execution settings
loglevel: DEBUG
logs_dir: logs
log_file: nih_export_log.txt
workers: 11

# 📂 Output settings
output_dir: results
preprocessed_dir: results/preprocessed
metrics_dir: results/study_metrics
keywords_dir: results/keywords
finalize_dir: results/finalize
